apiVersion: v1
kind: Service
metadata:
  name: tcube-uat-api-service
  namespace: tcube-uat
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: tcube-uat-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcube-uat-api
  namespace: tcube-uat
spec:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
  annotations:
    app.gitlab.com/app: PROJECT_SLUG
    app.gitlab.com/env: ENVIRONMENT_SLUG
spec:
  selector:
    matchLabels:
      app: tcube-uat-api
  replicas: 2
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: tcube-uat-api
      annotations:
        app.gitlab.com/app: PROJECT_SLUG
        app.gitlab.com/env: ENVIRONMENT_SLUG

    spec:
      containers:
      - name: tcube-uat-api
        image: registry.servx.global/products/tcube/api:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: deploykeys

